"""observation water_mask_geom overlay column

Revision ID: 35175aee5c62
Revises: cb96ab2f3b5e
Create Date: 2026-06-16 20:10:01.876595+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from geoalchemy2 import Geometry

revision: str = "35175aee5c62"
down_revision: str | None = "cb96ab2f3b5e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "observation",
        sa.Column(
            "water_mask_geom",
            Geometry(
                geometry_type="MULTIPOLYGON",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
    )
    op.create_index(
        "idx_observation_water_mask_geom",
        "observation",
        ["water_mask_geom"],
        unique=False,
        postgresql_using="gist",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_observation_water_mask_geom", table_name="observation", postgresql_using="gist"
    )
    op.drop_column("observation", "water_mask_geom")
    # ### end Alembic commands ###
