"""full schema: reservoir expand, gt, matches, rating curve, forcing, predictions

Revision ID: cb96ab2f3b5e
Revises: cca4d3c1ee50
Create Date: 2026-06-16 18:26:50.449539+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

revision: str = "cb96ab2f3b5e"
down_revision: str | None = "cca4d3c1ee50"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "model_version",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("model_name", sa.Text(), nullable=False),
        sa.Column("version", sa.Text(), nullable=False),
        sa.Column("mlflow_run_id", sa.Text(), nullable=True),
        sa.Column("model_stage", sa.Text(), nullable=False),
        sa.Column("trained_on_abt_version", sa.Text(), nullable=True),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "model_stage IN ('staging','production','archived')", name="ck_model_stage"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("model_name", "version", name="uq_model_version"),
    )
    op.create_table(
        "catchment_forcing",
        sa.Column("reservoir_id", sa.Text(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("catchment_precip", sa.Double(), nullable=True),
        sa.Column("antecedent_precip_index", sa.Double(), nullable=True),
        sa.Column("snow_cover_area", sa.Double(), nullable=True),
        sa.Column("swe", sa.Double(), nullable=True),
        sa.Column("degree_day_melt", sa.Double(), nullable=True),
        sa.Column("evaporation", sa.Double(), nullable=True),
        sa.Column("source_versions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("freshness_flags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["reservoir_id"],
            ["reservoir.reservoir_id"],
        ),
        sa.PrimaryKeyConstraint("reservoir_id", "date"),
    )
    op.create_table(
        "ground_truth",
        sa.Column("reservoir_id", sa.Text(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("level_m", sa.Numeric(precision=8, scale=3), nullable=True),
        sa.Column("live_storage_bcm", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("pct_filled", sa.Numeric(precision=6, scale=3), nullable=True),
        sa.Column("frl_m", sa.Numeric(precision=8, scale=3), nullable=False),
        sa.Column("live_capacity_bcm", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("normal_storage_pct", sa.Numeric(precision=6, scale=3), nullable=True),
        sa.Column("benefits_irr_cca", sa.Numeric(), nullable=True),
        sa.Column("benefits_hydel_mw", sa.Numeric(), nullable=True),
        sa.Column("source_pdf", sa.Text(), nullable=True),
        sa.Column("row_quality", sa.Text(), server_default="ok", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "row_quality IN ('ok','low_confidence','quarantine')", name="ck_gt_row_quality"
        ),
        sa.CheckConstraint("level_m IS NULL OR level_m >= 0", name="ck_gt_level_nonneg"),
        sa.CheckConstraint("pct_filled IS NULL OR pct_filled >= 0", name="ck_gt_pct_nonneg"),
        sa.ForeignKeyConstraint(
            ["reservoir_id"],
            ["reservoir.reservoir_id"],
        ),
        sa.PrimaryKeyConstraint("reservoir_id", "date"),
    )
    op.create_table(
        "pipeline_run",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("pipeline", sa.Text(), nullable=False),
        sa.Column("reservoir_id", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("row_counts", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("triggered_by", sa.Text(), nullable=True),
        sa.Column("contract_version", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "pipeline IN ('remote_sensing','data_engineering','ml')", name="ck_pipeline_name"
        ),
        sa.CheckConstraint(
            "status IN ('running','success','failed','quarantined')", name="ck_pipeline_status"
        ),
        sa.ForeignKeyConstraint(
            ["reservoir_id"],
            ["reservoir.reservoir_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "prediction",
        sa.Column("reservoir_id", sa.Text(), nullable=False),
        sa.Column("run_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("horizon_date", sa.Date(), nullable=False),
        sa.Column("predicted_level_m", sa.Double(), nullable=True),
        sa.Column("predicted_volume_bcm", sa.Double(), nullable=True),
        sa.Column("predicted_pct_filled", sa.Double(), nullable=True),
        sa.Column("interval_low", sa.Double(), nullable=True),
        sa.Column("interval_high", sa.Double(), nullable=True),
        sa.Column("model_version_id", sa.Uuid(), nullable=False),
        sa.Column("input_abt_version", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["model_version_id"],
            ["model_version.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reservoir_id"],
            ["reservoir.reservoir_id"],
        ),
        sa.PrimaryKeyConstraint("reservoir_id", "run_timestamp", "horizon_date"),
    )
    op.create_table(
        "rating_curve",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("reservoir_id", sa.Text(), nullable=False),
        sa.Column("version", sa.Text(), nullable=False),
        sa.Column("fit_type", sa.Text(), nullable=False),
        sa.Column(
            "area_to_storage_params", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("area_to_level_params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("curve_points", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("frl_anchor", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("observed_range", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("extrapolated_range", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("dem_epoch_waterline_m", sa.Numeric(precision=8, scale=3), nullable=True),
        sa.Column("dem_asset_id", sa.Text(), nullable=True),
        sa.Column("fit_metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("mlflow_run_id", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "fit_type IN ('empirical','dem_prior','blended')", name="ck_rating_curve_fit_type"
        ),
        sa.ForeignKeyConstraint(
            ["reservoir_id"],
            ["reservoir.reservoir_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("reservoir_id", "version", name="uq_rating_curve_version"),
    )
    op.create_index(
        "uq_rating_curve_one_active",
        "rating_curve",
        ["reservoir_id"],
        unique=True,
        postgresql_where=sa.text("is_active"),
    )
    op.create_table(
        "release_risk",
        sa.Column("reservoir_id", sa.Text(), nullable=False),
        sa.Column("run_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("release_probability", sa.Double(), nullable=False),
        sa.Column("risk_level", sa.Text(), nullable=False),
        sa.Column("estimated_lead_time_days", sa.Double(), nullable=True),
        sa.Column("contributing_factors", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("model_version_id", sa.Uuid(), nullable=False),
        sa.Column("input_abt_version", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "risk_level IN ('Low','Watch','Warning','Imminent')", name="ck_risk_level"
        ),
        sa.CheckConstraint(
            "release_probability >= 0 AND release_probability <= 1", name="ck_release_prob"
        ),
        sa.ForeignKeyConstraint(
            ["model_version_id"],
            ["model_version.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reservoir_id"],
            ["reservoir.reservoir_id"],
        ),
        sa.PrimaryKeyConstraint("reservoir_id", "run_timestamp"),
    )
    op.create_table(
        "reservoir_capacity_history",
        sa.Column("reservoir_id", sa.Text(), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("live_capacity_bcm", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("frl_m", sa.Numeric(precision=8, scale=3), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("live_capacity_bcm > 0", name="ck_capacity_history_positive"),
        sa.ForeignKeyConstraint(
            ["reservoir_id"],
            ["reservoir.reservoir_id"],
        ),
        sa.PrimaryKeyConstraint("reservoir_id", "valid_from"),
    )
    op.create_table(
        "ground_truth_match",
        sa.Column("reservoir_id", sa.Text(), nullable=False),
        sa.Column("gt_date", sa.Date(), nullable=False),
        sa.Column("extraction_version", sa.Text(), nullable=False),
        sa.Column("acquisition_date", sa.Date(), nullable=False),
        sa.Column("time_gap_days", sa.Integer(), nullable=False),
        sa.Column("scene_ids", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("extracted_area", sa.Double(), nullable=False),
        sa.Column("area_confidence", sa.Double(), nullable=False),
        sa.Column("extraction_method", sa.Text(), nullable=False),
        sa.Column("rating_curve_version", sa.Text(), nullable=True),
        sa.Column("derived_volume", sa.Double(), nullable=True),
        sa.Column("derived_level", sa.Double(), nullable=True),
        sa.Column("derived_pct_filled", sa.Numeric(precision=6, scale=3), nullable=True),
        sa.Column("residual_vs_ground_truth", sa.Double(), nullable=True),
        sa.Column("is_weak_label", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["reservoir_id", "gt_date"],
            ["ground_truth.reservoir_id", "ground_truth.date"],
            name="fk_gtmatch_ground_truth",
        ),
        sa.ForeignKeyConstraint(
            ["reservoir_id"],
            ["reservoir.reservoir_id"],
        ),
        sa.PrimaryKeyConstraint("reservoir_id", "gt_date", "extraction_version"),
    )
    op.add_column("analytical_base_table", sa.Column("evaporation", sa.Double(), nullable=True))
    op.add_column(
        "reservoir",
        sa.Column(
            "dam_point",
            Geometry(
                geometry_type="POINT",
                srid=4326,
                spatial_index=False,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
    )
    op.add_column(
        "reservoir",
        sa.Column(
            "aoi_geom",
            Geometry(
                geometry_type="MULTIPOLYGON",
                srid=4326,
                spatial_index=False,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
    )
    op.add_column("reservoir", sa.Column("aoi_version", sa.Text(), nullable=False))
    op.add_column(
        "reservoir",
        sa.Column(
            "catchment_geom",
            Geometry(
                geometry_type="MULTIPOLYGON",
                srid=4326,
                spatial_index=False,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
    )
    op.add_column("reservoir", sa.Column("catchment_version", sa.Text(), nullable=True))
    op.add_column(
        "reservoir",
        sa.Column("release_thresholds", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    )
    op.add_column(
        "reservoir",
        sa.Column("rating_curve_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "reservoir", sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False)
    )
    op.add_column(
        "reservoir",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.create_index(
        "idx_reservoir_aoi_geom", "reservoir", ["aoi_geom"], unique=False, postgresql_using="gist"
    )
    op.create_index(
        "idx_reservoir_catchment_geom",
        "reservoir",
        ["catchment_geom"],
        unique=False,
        postgresql_using="gist",
    )
    op.create_index(
        "idx_reservoir_dam_point", "reservoir", ["dam_point"], unique=False, postgresql_using="gist"
    )
    # ### end Alembic commands ###

    # Append-only audit trail (NFR-REL-5): prediction + release_risk reject UPDATE/DELETE.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION forbid_mutation() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'append-only table %: % is not permitted', TG_TABLE_NAME, TG_OP;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        "CREATE TRIGGER trg_prediction_append_only BEFORE UPDATE OR DELETE ON prediction "
        "FOR EACH ROW EXECUTE FUNCTION forbid_mutation();"
    )
    op.execute(
        "CREATE TRIGGER trg_release_risk_append_only BEFORE UPDATE OR DELETE ON release_risk "
        "FOR EACH ROW EXECUTE FUNCTION forbid_mutation();"
    )

    # abt_current: latest abt_version per (reservoir_id, date) — the contract grain (FR-ABT-4).
    op.execute(
        """
        CREATE VIEW abt_current AS
        SELECT DISTINCT ON (reservoir_id, date) *
        FROM analytical_base_table
        ORDER BY reservoir_id, date, abt_version DESC;
        """
    )


def downgrade() -> None:
    op.execute("DROP VIEW IF EXISTS abt_current;")
    # Drop append-only triggers + function (triggers also drop with their tables below).
    op.execute("DROP TRIGGER IF EXISTS trg_release_risk_append_only ON release_risk;")
    op.execute("DROP TRIGGER IF EXISTS trg_prediction_append_only ON prediction;")
    op.execute("DROP FUNCTION IF EXISTS forbid_mutation();")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_reservoir_dam_point", table_name="reservoir", postgresql_using="gist")
    op.drop_index("idx_reservoir_catchment_geom", table_name="reservoir", postgresql_using="gist")
    op.drop_index("idx_reservoir_aoi_geom", table_name="reservoir", postgresql_using="gist")
    op.drop_column("reservoir", "updated_at")
    op.drop_column("reservoir", "is_active")
    op.drop_column("reservoir", "rating_curve_config")
    op.drop_column("reservoir", "release_thresholds")
    op.drop_column("reservoir", "catchment_version")
    op.drop_column("reservoir", "catchment_geom")
    op.drop_column("reservoir", "aoi_version")
    op.drop_column("reservoir", "aoi_geom")
    op.drop_column("reservoir", "dam_point")
    op.drop_column("analytical_base_table", "evaporation")
    op.drop_table("ground_truth_match")
    op.drop_table("reservoir_capacity_history")
    op.drop_table("release_risk")
    op.drop_index(
        "uq_rating_curve_one_active",
        table_name="rating_curve",
        postgresql_where=sa.text("is_active"),
    )
    op.drop_table("rating_curve")
    op.drop_table("prediction")
    op.drop_table("pipeline_run")
    op.drop_table("ground_truth")
    op.drop_table("catchment_forcing")
    op.drop_table("model_version")
    # ### end Alembic commands ###
